prompts = [
    # Nature
    "Tree",
    "Flower",
    "Mushroom",
    "Cactus",
    "Leaf",
    "Mountain",
    "Cloud",
    "Rainbow",
    "River",
    "Campfire",
    "Waterfall",
    "Snowflake",
    "Sunset",
    "Star",
    "Planet",
    # Animals
    "Cat",
    "Dog",
    "Fox",
    "Wolf",
    "Bear",
    "Rabbit",
    "Frog",
    "Owl",
    "Penguin",
    "Duck",
    "Turtle",
    "Snake",
    "Fish",
    "Shark",
    "Whale",
    "Butterfly",
    "Bee",
    "Ladybug",
    "Spider",
    "Dragon",
    # Food & Drinks
    "Apple",
    "Strawberry",
    "Watermelon",
    "Banana",
    "Pizza",
    "Burger",
    "Fries",
    "Ice Cream",
    "Donut",
    "Cake",
    "Cupcake",
    "Coffee",
    "Tea",
    "Soda Can",
    "Sushi",
    # Fantasy
    "Wizard",
    "Knight",
    "Witch",
    "Elf",
    "Fairy",
    "Unicorn",
    "Goblin",
    "Treasure Chest",
    "Magic Potion",
    "Crystal Ball",
    "Spell Book",
    "Sword",
    "Shield",
    "Crown",
    # Sci-Fi
    "Robot",
    "Alien",
    "UFO",
    "Spaceship",
    "Astronaut",
    "Satellite",
    "Laser",
    "Energy Crystal",
    "Space Station",
    "Futuristic City",
    # Buildings
    "House",
    "Cabin",
    "Castle",
    "Windmill",
    "Lighthouse",
    "Barn",
    "Shop",
    "Tower",
    "Bridge",
    "Temple",
    # Vehicles
    "Car",
    "Bike",
    "Motorcycle",
    "Train",
    "Airplane",
    "Helicopter",
    "Boat",
    "Sailboat",
    "Submarine",
    "Rocket",
    # Everyday Objects
    "Book",
    "Clock",
    "Lamp",
    "Candle",
    "Backpack",
    "Glasses",
    "Headphones",
    "Camera",
    "Game Controller",
    "Computer",
    "Phone",
    "TV",
    "Chair",
    "Potted Plant",
    # Weather
    "Sun",
    "Moon",
    "Lightning",
    "Snowman",
    "Umbrella",
    "Tornado",
    "Storm Cloud",
    "Raindrop",
    "Wind Gust",
    # Holidays
    "Pumpkin",
    "Ghost",
    "Bat",
    "Present",
    "Candy Cane",
    "Fireworks",
    # Video Game Characters
    "Mario",
    "Luigi",
    "Princess Peach",
    "Bowser",
    "Link",
    "Zelda",
    "Kirby",
    "Pikachu",
    "Sonic the Hedgehog",
    "Tails",
    "Knuckles",
    "Mega Man",
    "Pac-Man",
    "Donkey Kong",
    "Yoshi",
    "Steve",
    "Creeper",
    "Enderman",
    "Cuphead",
    "Crash Bandicoot",
    "Spyro",
    # Superheroes
    "Batman",
    "Superman",
    "Wonder Woman",
    "Spider-Man",
    "Iron Man",
    "Captain America",
    "Thor",
    "Hulk",
    "Wolverine",
    "Deadpool",
    "Black Panther",
    "Doctor Strange",
    "The Flash",
    "Green Lantern",
    "Aquaman",
    "Harley Quinn",
    "Joker",
    "Catwoman",
    # Star Wars
    "Darth Vader",
    "Chewbacca",
    "Yoda",
    "Darth Maul",
    "Stormtrooper",
    "R2-D2",
    "C-3PO",
    # Disney & Pixar
    "Mickey Mouse",
    "Minnie Mouse",
    "Donald Duck",
    "Goofy",
    "Stitch",
    "Winnie the Pooh",
    "Buzz Lightyear",
    "Woody",
    "Lightning McQueen",
    # TV & Cartoons
    "SpongeBob SquarePants",
    "Patrick Star",
    "Squidward",
    "Scooby-Doo",
    "Shaggy",
    "Tom",
    "Jerry",
    "Bugs Bunny",
    "Daffy Duck",
    "Homer Simpson",
    "Bart Simpson",
    # Movie Characters
    "Shrek",
    "The Terminator",
    "RoboCop",
    # Comic & Pop Culture
    "Hello Kitty",
    "Snoopy",
    "Garfield",
    "Charlie Brown",
    "Popeye",
    "The Pink Panther",
    "Smurf",
]

palettes = [
    "nostalgia",
    "nes-advanced",
    "endesga-32",
    "endesga-16",
    "sweetie-16",
    "pico-8",
    "1bit-monitor-glow",
    "punolite-plus-plus",
]
